# This is a basic workflow to help you get started with Actions

name: HCL AppScan on Cloud SAST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the AltoroJ-3.2 branch
  push:
    branches: [ AltoroJ-3.2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Main Repo
        uses: actions/checkout@v2
          
      # Runs a set of commands using the runners shell
      - name: Gradle Build
        run: |
          ls -la
          #gradle build
          
      # Runs AppScan Step
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.6
        with:
          asoc_key: ${{secrets.ASOC_API_KEY}}
          asoc_secret: ${{secrets.ASOC_API_SECRET}}
          application_id: ${{secrets.ASOC_APPID}}
          wait_for_analysis: true
          analysis_timeout_minutes: 20
          fail_for_noncompliance: true
          
